### ISSUE TITLE
Proper network configuration of Maraki MX60

### ISSUE THREAD

**Issue by songokumanjimaru** [riptidewave93/LEDE-MX60#1]
Hi Github community

I recently do the flashing process of Meraki MX60, but at the end I no get communication with device via ethernet.

I modifi the network configuration from this

config switch_vlan
        option device 'switch0'
        option vlan '1'
        option ports '1 2 3 4 5t'

config switch_vlan
        option device 'switch0'
        option vlan '2'
        option ports '0 5t'

To this

config switch_vlan
        option device 'switch0'
        option vlan '1'
        option ports '0t 1 2 3 4 5'

config switch_vlan
        option device 'switch0'
        option vlan '2'
        option ports '0t 5'

And my Meraki is working very well, I suggest to modify the flashing process at the final part. My sugestion is to change the network config file, ad tell to the user tat change the ethernet port fro WAN to LAN.

Best regards

**Comment by riptidewave93** [comment]
What version was flashed? Did you do a build from this repo, or use an upstream image?

**Comment by riptidewave93** [comment]
Closing due to lack of reply
